[package]
name = "czytaj"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13", features = ["tokio", "tiny-skia"], default-features = false }
reqwest = "0.12"
feed-rs = "2.1"
tokio = { version = "1", features = ["full"] }
regex = "1"
html-escape = "0.2"
once_cell = "1"
