[package]
name = "czytaj"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13", features = ["tokio"] }
reqwest = { version = "0.12", features = ["blocking"] }
feed-rs = "2.1"
tokio = { version = "1", features = ["full"] }
